version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./core:/var/www/html/core
    depends_on:
      - php
      - postgres

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: on-failure
    volumes:
      - ./core:/var/www/html/core
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: education
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
