vich_uploader:
    db_driver: orm
    mappings:
        file:
            uri_prefix: '/images'
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true

        userImage:
            uri_prefix: '/images'
            upload_destination: '%kernel.project_dir%/public/userImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true